twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        nom: 'Salmon'
        prenom: 'Étienne'
        mail: 'barbapapan25@gmail.com'
        telephone: '06 32 51 85 85'
        facebook: 'Etienne Salmon'
        youtube: 'Etienne Salmon'
        instagram : 'Etienne Salmon TDM'
        tiktok : 'Barbapapan'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        strict_variables: true
