twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        nom: 'Salmon'
        prenom: 'Étienne'
        mailContact: 'contact@faotravel.fr'
        mailFAO: 'barbapapan25@gmail.com'
        mailWM: 'g.salmon@free.fr'
        telephone: '06 32 51 85 85'
        facebook: 'https://www.facebook.com/salmon.etienne'
        youtube: 'https://www.youtube.com/channel/UCJmuI3OdfHtrI7L-Gf2OeDg'
        instagram : 'https://www.instagram.com/etienne.salmon/?hl=fr'
        tiktok : 'https://www.tiktok.com/@barbapapan'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/images': images
when@test:
    twig:
        strict_variables: true
