vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        medias:
            uri_prefix: /uploads/medias
            upload_destination: '%kernel.project_dir%/public/uploads/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        logos:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        illustrations:
            uri_prefix: /uploads/illustrations
            upload_destination: '%kernel.project_dir%/public/uploads/illustrations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        coupures:
            uri_prefix: /uploads/coupures
            upload_destination: '%kernel.project_dir%/public/uploads/coupures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
