vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        coupures:
            uri_prefix: /uploads/coupures
            upload_destination: '%kernel.project_dir%/public/uploads/coupures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        photos:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
