vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        medias:
            uri_prefix: /uploads/medias
            upload_destination: '%kernel.project_dir%/public/uploads/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
