name: test
on:
  push:
    branches:
    - main

env:
  FIRST_NAME: Gilles
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /FAO
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
          host: ${{ secrets.APP_HOST }}
          user: root
          key: ${{ secrets.APP_KEY}}
          pass: ${{ secrets.APP_PASS }}
          args: "-tt -vvv"
