name: test
on:
  push:
    branches:
    - main

env:
  FIRST_NAME: Gilles
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: ${{ secrets.APP_HOST }}
        username: ${{ secrets.APP_USER }}
        passphrase: ${{ secrets.APP_PASS }}
        privateKey: ${{ secrets.APP_KEY }} 
